<?php
error_reporting(E_ALL ^ E_NOTICE);
session_status() === PHP_SESSION_ACTIVE || session_start();

if(!isset($_SESSION["user"]) || empty($_SESSION["user"])){
    header("Location: bejelentkezes.php?hiba=true");
    exit();
} else {
    $felhasznalonev = $_SESSION["user"]["felhasznalonev"];
}

if(isset($_POST['megerosites'])) {
    $egyikJaratszam=$_POST['post-jaratszam-egyik'];
    $masikJaratszam = $_POST['post-jaratszam-masik'] ?? '';
    $felnott=$_POST['post-felnott'];
    $gyermek=$_POST['post-gyermek'];
}

include_once("common/connection.php");
$utazasiiroda = csatlakozas();

/*
 * ID NUMBER(4) GENERATED BY DEFAULT AS IDENTITY(START with 6 INCREMENT by 1) PRIMARY KEY NOT NULL,
    AR NUMBER(8) NOT NULL,
    TIPUS NUMBER(1) NOT NULL,                --0: GYEREK, 1: FELNOTT
    FELHASZNALONEV VARCHAR(20),
    JARATSZAM NUMBER(4) NOT NULL,
*/

// MENTÉS AZ ADATBÁZISBA
if(isset($_POST['foglalas'])) {
    $egyikJarat = $_POST['jaratszam-vegso-egyik'];
    $ar = $_POST['post-ara'];
    $felnott = $_POST['felnott'];
    $gyermek = $_POST['gyermek'];
    $felnottArTomb = $_POST['felnottArTomb'];
    $gyermekArTomb = $_POST['gyermekArTomb'];
    $felnottArTombMasik = $_POST['felnottArTombMasik'];
    $gyermekArTombMasik = $_POST['gyermekArTombMasik'];
    for($i = 0; $i < $felnott; ++$i) {
        $felnottFoglalas = oci_parse($utazasiiroda, "INSERT INTO JEGY (AR, TIPUS, FELHASZNALONEV, JARATSZAM) VALUES ('$felnottArTomb[$i]', 1, '$felhasznalonev', '$egyikJarat')");
        oci_execute($felnottFoglalas) or die('Hiba');

        if(isset($_POST['jaratszam-vegso-masik'])) {
            $masikJarat = $_POST['jaratszam-vegso-masik'];
            $felnottFoglalas = oci_parse($utazasiiroda, "INSERT INTO JEGY (AR, TIPUS, FELHASZNALONEV, JARATSZAM) VALUES ('$felnottArTombMasik[$i]', 1, '$felhasznalonev', '$masikJarat')");
            oci_execute($felnottFoglalas) or die('Hiba');
        }
    }
    if($gyermek > 0) {
        for($i = 0; $i < $gyermek; ++$i) {
            $gyermekFoglalas = oci_parse($utazasiiroda, "INSERT INTO JEGY (AR, TIPUS, FELHASZNALONEV, JARATSZAM) VALUES ('$gyermekArTomb[$i]', 0, '$felhasznalonev', '$egyikJarat')");
            oci_execute($gyermekFoglalas) or die('Hiba');

            if(isset($_POST['jaratszam-vegso-masik'])) {
                $masikJarat = $_POST['jaratszam-vegso-masik'];
                $gyermekFoglalas = oci_parse($utazasiiroda, "INSERT INTO JEGY (AR, TIPUS, FELHASZNALONEV, JARATSZAM) VALUES ('$gyermekArTombMasik[$i]', 0, '$felhasznalonev', '$masikJarat')");
                oci_execute($gyermekFoglalas) or die('Hiba');
            }
        }
    }
    header("Location: profil.php?foglalas=true");
}

if((!isset($_POST['post-felnott']) && !isset($_POST['foglalas']) && !isset($_POST['post-gyermek']))) {
    header("Location: jegyfoglalas.php?hibas=true");
}
?>
<!DOCTYPE html>
<html lang="hu">
<head>
    <meta charset="UTF-8">
    <title>Irinyi utazási iroda</title>
    <link rel="icon" href="img/negyedikicon.png"/>
    <link rel="stylesheet" href="css/style.css"/>
    <link rel="stylesheet" href="css/foglalas.css"/>
</head>
<body>
<?php
    include_once("common/header.php");
    include_once("common/fuggvenyek.php");
    menuGeneralas('jegyfoglalas');
?>
<main>
<div class="container">
    <div class="jarat-adatok">
        <table id="repjegy-dijtetelei">
        <caption>Repülőjegy díjtételei:</caption>
            <?php
            $felnottArTomb = [];
            $felnottArTombMasik = [];
            $gyermekArTomb = [];
            $gyermekArTombMasik = [];
            $alapar=0;
            $egyikRepjegyAra = repulojegyAra($egyikJaratszam) ;
            $masikRepjegyAra = isset($_POST['post-jaratszam-masik']) ? repulojegyAra($masikJaratszam) : 0;
            if($masikRepjegyAra === 0) {
                echo '<tr>';
                    echo '<th>Felnőtt alapár</th>';
                    echo '<td>' . $felnott . ' x ' . number_format($egyikRepjegyAra) . ' Ft' . '</td>';
                echo '</tr>';
                $alapar+=$felnott*$egyikRepjegyAra;
                for($i = 0; $i < $felnott; ++$i) {
                    array_push($felnottArTomb,$egyikRepjegyAra);
                }
                if($gyermek > 0) {
                    echo '<tr>';
                        echo '<th>Gyermek alapár</th>';
                        echo '<td>' . $gyermek . ' x ' . number_format($egyikRepjegyAra) . ' Ft' . '</td>';
                    echo '</tr>';
                    $alapar+=$gyermek*$egyikRepjegyAra;
                    for($i = 0; $i < $felnott; ++$i) {
                        array_push($gyermekArTomb,$egyikRepjegyAra);
                    }
                }
            } else {
                echo '<tr>';
                echo '<th>Felnőtt alapár</th>';
                echo '<td>' . $felnott . ' x ' . number_format($egyikRepjegyAra) . ' Ft' . '</td>';
                echo '<td>' . $felnott . ' x ' . number_format($masikRepjegyAra) . ' Ft' . '</td>';
                echo '</tr>';
                $alapar+=$felnott*($egyikRepjegyAra+$masikRepjegyAra);
                for($i = 0; $i < $felnott; ++$i) {
                    array_push($felnottArTomb,$egyikRepjegyAra);
                    array_push($felnottArTombMasik,$masikRepjegyAra);
                }
                if($gyermek > 0) {
                    echo '<tr>';
                    echo '<th>Gyermek alapár</th>';
                    echo '<td>' . $gyermek . ' x ' . number_format($egyikRepjegyAra) . ' Ft' . '</td>';
                    echo '<td>' . $gyermek . ' x ' . number_format($masikRepjegyAra) . ' Ft' . '</td>';
                    echo '</tr>';
                    $alapar+=$gyermek*($egyikRepjegyAra+$masikRepjegyAra);
                    for($i = 0; $i < $felnott; ++$i) {
                        array_push($gyermekArTomb,$egyikRepjegyAra);
                        array_push($gyermekArTombMasik,$masikRepjegyAra);
                    }
                }
            }


            $etkezes_ara = 0;
            if(etkezes($egyikJaratszam) === 1) {
                // ÉTKEZÉS ÁRAK - FELNŐTT
                $etkezes_szamlalo = 0;
                for ($i = 1; $i <= $felnott; ++$i) {
                    if (isset($_POST['etkezes-felnőtt-' . $i])) {
                        $etkezes_szamlalo++;
                        $felnottArTomb[$i - 1] += 5720;
                        $felnottArTombMasik[$i - 1] += 5720;
                    }
                }

                // ÉTKEZÉS ÁRAK - GYERMEK
                if ($gyermek > 0) {
                    for ($i = 1; $i <= $gyermek; ++$i) {
                        if (isset($_POST['etkezes-gyermek-' . $i])) {
                            $etkezes_szamlalo++;
                            $gyermekArTomb[$i - 1] += 5720;
                            $gyermekArTombMasik[$i - 1] += 5720;
                        }
                    }
                }

                echo '<tr>';
                    echo '<th>Étkezés</th>';
                    echo '<td>' . $etkezes_szamlalo . ' x 5,720 Ft' . '</td>';
                echo '</tr>';
                $etkezes_ara = $etkezes_szamlalo*5720;
            }

            echo '<tr>';
                echo '<th>Kezelési költség</th>';
                echo '<td>1 x 214 Ft</td>';
                $kezelesi=214;
            echo '</tr>';

            // OSSZEGEK SZUMMAZASA
            echo '<tr>';
                echo '<th>Összesen:</th>';
                echo '<td>' . number_format($alapar + $etkezes_ara + $kezelesi) . ' Ft' . '</td>';
            echo '</tr>';
            ?>
        </table>
        <form method="post" action="jegyfoglalas_megerosites.php">
            <div id="szabaly-checkbox">
                <label for="szabalyzat-elfogadas">
                    <input type="checkbox" id="szabalyzat-elfogadas" name="szabalyzat" required>
                    A repülőjegy megvásárlásával elfogadom az irinyiutazasiiroda.hu szabályzatát.
                </label> <br/>
                <label for="18-felett">
                    <input type="checkbox" id="18-felett" name="szabalyzat" required>
                    Büntetőjogi felelősségem teljes tudatában kijelentem, hogy elmúltam 18 éves.
                </label> <br/>
            </div>
            <?php
            echo '<input type="hidden" name="jaratszam-vegso-egyik" value=' . $egyikJaratszam . '>';
            echo isset($_POST['post-jaratszam-masik']) ? '<input type="hidden" name="jaratszam-vegso-masik" value=' . $masikJaratszam . '>' : '';
            echo '<input type="hidden" name="felnott" value=' . $felnott . '>';
            echo '<input type="hidden" name="gyermek" value=' . $gyermek . '>';
            foreach($felnottArTomb as $tombElem) {
                echo '<input type="hidden" name="felnottArTomb[]" value=' . $tombElem . '>';
            }
            foreach($gyermekArTomb as $tombElem) {
                echo '<input type="hidden" name="gyermekArTomb[]" value=' . $tombElem . '>';
            }
            if($masikRepjegyAra !== 0) {
                foreach ($felnottArTombMasik as $tombElem) {
                    echo '<input type="hidden" name="felnottArTombMasik[]" value=' . $tombElem . '>';
                }
                foreach ($gyermekArTombMasik as $tombElem) {
                    echo '<input type="hidden" name="gyermekArTombMasik[]" value=' . $tombElem . '>';
                }
            }
            ?>
            <input type="submit" name="foglalas" value="Foglalás">
        </form>
    </div>
</div>
</main>
</body>
</html>
<?php
    if(isset($felnottFoglalas) && is_resource($felnottFoglalas)) {
        oci_free_statement($felnottFoglalas);
    }

    if(isset($gyermekFoglalas) && is_resource($gyermekFoglalas)) {
        oci_free_statement($gyermekFoglalas);
    }

    csatlakozas_zarasa($utazasiiroda);
?>